"""Compile canonical skill metadata into checked-in human and machine views."""

from __future__ import annotations

import argparse
import json
import shlex
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "skills" / "catalog.json"
EVALUATION = ROOT / "docs" / "evaluation-inventory.json"
INVENTORY = ROOT / "docs" / "skill-inventory.md"
STATE = ROOT / "docs" / "skill-state.json"
HEADER = "| Name | Purpose | Primary trigger / use case | Maturity | Implementation depth | Evaluation level | Provenance | Overlapping / adjacent skills |"


def read_json(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path.relative_to(ROOT)}: invalid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{path.relative_to(ROOT)}: expected an object")
    return value


def compile_registry(root: Path = ROOT) -> dict:
    catalog = read_json(root / "skills" / "catalog.json")
    evaluation = read_json(root / "docs" / "evaluation-inventory.json")
    records = catalog.get("skills")
    evidence = evaluation.get("skills")
    if not isinstance(records, list) or not isinstance(evidence, dict):
        raise ValueError("catalog skills and evaluation skills must be present")

    names = [record.get("name") for record in records if isinstance(record, dict)]
    if len(names) != len(set(names)):
        raise ValueError("catalog skill names are not unique")
    if set(names) != set(evidence):
        raise ValueError("catalog and evaluation coverage differ")

    skills = []
    for record in records:
        if not isinstance(record, dict):
            raise ValueError("catalog records must be objects")
        name = record.get("name")
        evaluation_record = evidence.get(name)
        required = ("classification", "primary_trigger", "provenance")
        if any(not isinstance(record.get(field), str) or not record[field] for field in required):
            raise ValueError(f"{name}: classification, primary_trigger, and provenance are required")
        if not isinstance(evaluation_record, dict):
            raise ValueError(f"{name}: evaluation record must be an object")
        if set(evaluation_record) != {"level", "evidence", "command"}:
            raise ValueError(f"{name}: evaluation must contain level, evidence, and command")
        evidence_path = evaluation_record["evidence"]
        if evidence_path != "none" and not (root / evidence_path).is_file():
            raise ValueError(f"{name}: missing evaluation evidence {evidence_path}")
        command = evaluation_record["command"]
        if command.startswith("python scripts/"):
            command_path = shlex.split(command)[1]
            if not (root / command_path).is_file():
                raise ValueError(f"{name}: missing evaluation command runner {command_path}")
        relationships = set(record.get("related_skills", [])) | set(record.get("intentional_overlaps", []))
        if relationships - set(names):
            raise ValueError(f"{name}: relationship points to unknown skill")
        skill = {
            "name": name,
            "path": record.get("path"),
            "description": record.get("description"),
            "primary_trigger": record["primary_trigger"],
            "classification": record["classification"],
            "implementation_depth": record.get("capability_level"),
            "evaluation": evaluation_record,
            "provenance": record["provenance"],
            "related_skills": record.get("related_skills", []),
            "intentional_overlaps": record.get("intentional_overlaps", []),
        }
        skills.append(skill)

    return {
        "version": 1,
        "source": {"catalog": "skills/catalog.json", "evaluation": "docs/evaluation-inventory.json"},
        "counts": {
            "skills": len(skills),
            "by_classification": _counts(skills, "classification"),
            "by_evaluation_level": _counts(skills, lambda skill: skill["evaluation"]["level"]),
        },
        "skills": skills,
    }


def _counts(items: list[dict], field) -> dict[str, int]:
    values = [field(item) if callable(field) else item[field] for item in items]
    return {value: values.count(value) for value in sorted(set(values))}


def inventory_text(registry: dict) -> str:
    lines = [
        "# Skill inventory",
        "",
        "This file is generated by `python scripts/compile_skill_registry.py`.",
        "Canonical metadata lives in [`skills/catalog.json`](../skills/catalog.json)",
        "and [`evaluation-inventory.json`](evaluation-inventory.json); edit those",
        "sources, then regenerate this view.",
        "",
        HEADER,
        "|---|---|---|---|---|---|---|---|",
    ]
    for skill in registry["skills"]:
        overlaps = ", ".join(skill["related_skills"]) or "—"
        if skill["intentional_overlaps"]:
            overlaps += "; intentional overlap: " + ", ".join(skill["intentional_overlaps"])
        lines.append("| " + " | ".join([
            f"`{skill['name']}`",
            skill["description"],
            skill["primary_trigger"],
            skill["classification"],
            skill["implementation_depth"],
            skill["evaluation"]["level"],
            skill["provenance"],
            overlaps,
        ]) + " |")
    return "\n".join(lines) + "\n"


def render(root: Path = ROOT) -> tuple[str, str]:
    registry = compile_registry(root)
    state = json.dumps(registry, indent=2, ensure_ascii=False) + "\n"
    return inventory_text(registry), state


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated views are stale")
    args = parser.parse_args(argv)
    try:
        inventory, state = render()
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 1
    expected = {INVENTORY: inventory, STATE: state}
    stale = [str(path.relative_to(ROOT)) for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("stale generated views: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("SKILL_REGISTRY_OK")
        return 0
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8", newline="\n")
    print("generated: " + ", ".join(str(path.relative_to(ROOT)) for path in expected))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
